version: '3.8'

networks:
  airflow-net:

services:
  airflow:
    image: apache/airflow:3.0.3-python3.10
    container_name: putusan-airflow
    networks:
      - airflow-net
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/airflow/project
      - ./airflow/dags:/opt/airflow/project/dags
      - ./airflow/plugins:/opt/airflow/project/plugins
    environment:
      AIRFLOW_HOME: /opt/airflow/project
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    command: >
      bash -c "cd /opt/airflow/project && pip install -r requirements.txt && airflow standalone"

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: putusan-clickhouse
    networks:
      - airflow-net
    ports:
      - "8123:8123"
      - "5473:5473"
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: default
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  minio:
    image: quay.io/minio/minio
    container_name: putusan-minio
    networks:
      - airflow-net
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
